"""empty message

Revision ID: 04f96e896496
Revises: 
Create Date: 2020-03-11 13:23:21.178177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04f96e896496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orderdetails_ibfk_1', 'orderdetails', type_='foreignkey')
    op.drop_column('orderdetails', 'product_id')
    op.drop_column('orderdetails', 'order_id')
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer_id')
    op.drop_constraint('payment_ibfk_1', 'payment', type_='foreignkey')
    op.drop_column('payment', 'order_id')
    op.add_column('products', sa.Column('pid', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_products_pid'), 'products', ['pid'], unique=False)
    op.drop_index('ix_products_id', table_name='products')
    op.drop_column('products', 'id')
    op.drop_constraint('rating_ibfk_2', 'rating', type_='foreignkey')
    op.drop_column('rating', 'product_id')
    op.drop_constraint('shippers_ibfk_1', 'shippers', type_='foreignkey')
    op.drop_column('shippers', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shippers', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('shippers_ibfk_1', 'shippers', 'orders', ['order_id'], ['id'])
    op.add_column('rating', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('rating_ibfk_2', 'rating', 'products', ['product_id'], ['id'])
    op.add_column('products', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.drop_index(op.f('ix_products_pid'), table_name='products')
    op.drop_column('products', 'pid')
    op.add_column('payment', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('payment_ibfk_1', 'payment', 'orders', ['order_id'], ['id'])
    op.add_column('orders', sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_ibfk_1', 'orders', 'customers', ['customer_id'], ['id'])
    op.add_column('orderdetails', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('orderdetails', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('orderdetails_ibfk_1', 'orderdetails', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
