"""empty message

Revision ID: 201bb8555a09
Revises: 
Create Date: 2020-02-29 01:44:56.206812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201bb8555a09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=60), nullable=False),
    sa.Column('lname', sa.String(length=60), nullable=False),
    sa.Column('phone1', sa.String(length=60), nullable=False),
    sa.Column('phone2', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('pword', sa.String(length=100), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=False)
    op.create_index(op.f('ix_admin_fname'), 'admin', ['fname'], unique=False)
    op.create_index(op.f('ix_admin_lname'), 'admin', ['lname'], unique=False)
    op.create_index(op.f('ix_admin_phone1'), 'admin', ['phone1'], unique=False)
    op.create_index(op.f('ix_admin_phone2'), 'admin', ['phone2'], unique=False)
    op.create_index(op.f('ix_admin_pword'), 'admin', ['pword'], unique=False)
    op.create_index(op.f('ix_admin_timeStamp'), 'admin', ['timeStamp'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=60), nullable=False),
    sa.Column('lname', sa.String(length=60), nullable=False),
    sa.Column('phone1', sa.String(length=60), nullable=False),
    sa.Column('phone2', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('pword', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=60), nullable=True),
    sa.Column('additionalInfo', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_additionalInfo'), 'customers', ['additionalInfo'], unique=False)
    op.create_index(op.f('ix_customers_address'), 'customers', ['address'], unique=False)
    op.create_index(op.f('ix_customers_city'), 'customers', ['city'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_fname'), 'customers', ['fname'], unique=False)
    op.create_index(op.f('ix_customers_lname'), 'customers', ['lname'], unique=False)
    op.create_index(op.f('ix_customers_phone1'), 'customers', ['phone1'], unique=False)
    op.create_index(op.f('ix_customers_pword'), 'customers', ['pword'], unique=False)
    op.create_index(op.f('ix_customers_region'), 'customers', ['region'], unique=False)
    op.create_index(op.f('ix_customers_timeStamp'), 'customers', ['timeStamp'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_timeStamp'), 'orders', ['timeStamp'], unique=False)
    op.create_table('orderdetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('fulfilledDate', sa.String(length=20), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderdetails_color'), 'orderdetails', ['color'], unique=False)
    op.create_index(op.f('ix_orderdetails_discount'), 'orderdetails', ['discount'], unique=False)
    op.create_index(op.f('ix_orderdetails_fulfilledDate'), 'orderdetails', ['fulfilledDate'], unique=False)
    op.create_index(op.f('ix_orderdetails_price'), 'orderdetails', ['price'], unique=False)
    op.create_index(op.f('ix_orderdetails_quantity'), 'orderdetails', ['quantity'], unique=False)
    op.create_index(op.f('ix_orderdetails_size'), 'orderdetails', ['size'], unique=False)
    op.create_index(op.f('ix_orderdetails_timeStamp'), 'orderdetails', ['timeStamp'], unique=False)
    op.create_index(op.f('ix_orderdetails_total'), 'orderdetails', ['total'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transactionCode', sa.String(length=60), nullable=False),
    sa.Column('paidTotal', sa.Integer(), nullable=False),
    sa.Column('shipperPrice', sa.Integer(), nullable=False),
    sa.Column('dripQuota', sa.Integer(), nullable=False),
    sa.Column('dripQuotaTotal', sa.Integer(), nullable=False),
    sa.Column('sellerReturns', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_dripQuota'), 'payment', ['dripQuota'], unique=False)
    op.create_index(op.f('ix_payment_dripQuotaTotal'), 'payment', ['dripQuotaTotal'], unique=False)
    op.create_index(op.f('ix_payment_paidTotal'), 'payment', ['paidTotal'], unique=False)
    op.create_index(op.f('ix_payment_sellerReturns'), 'payment', ['sellerReturns'], unique=False)
    op.create_index(op.f('ix_payment_shipperPrice'), 'payment', ['shipperPrice'], unique=False)
    op.create_index(op.f('ix_payment_timeStamp'), 'payment', ['timeStamp'], unique=False)
    op.create_index(op.f('ix_payment_total'), 'payment', ['total'], unique=False)
    op.create_index(op.f('ix_payment_transactionCode'), 'payment', ['transactionCode'], unique=False)
    op.create_table('shippers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyName', sa.String(length=60), nullable=False),
    sa.Column('companyLogo', sa.String(length=60), nullable=False),
    sa.Column('phone1', sa.String(length=60), nullable=False),
    sa.Column('phone2', sa.String(length=60), nullable=True),
    sa.Column('email1', sa.String(length=60), nullable=False),
    sa.Column('email2', sa.String(length=60), nullable=True),
    sa.Column('address', sa.String(length=60), nullable=False),
    sa.Column('additionalInfo', sa.String(length=60), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shippers_additionalInfo'), 'shippers', ['additionalInfo'], unique=False)
    op.create_index(op.f('ix_shippers_address'), 'shippers', ['address'], unique=False)
    op.create_index(op.f('ix_shippers_city'), 'shippers', ['city'], unique=False)
    op.create_index(op.f('ix_shippers_companyLogo'), 'shippers', ['companyLogo'], unique=False)
    op.create_index(op.f('ix_shippers_companyName'), 'shippers', ['companyName'], unique=False)
    op.create_index(op.f('ix_shippers_email1'), 'shippers', ['email1'], unique=False)
    op.create_index(op.f('ix_shippers_email2'), 'shippers', ['email2'], unique=False)
    op.create_index(op.f('ix_shippers_phone1'), 'shippers', ['phone1'], unique=False)
    op.create_index(op.f('ix_shippers_phone2'), 'shippers', ['phone2'], unique=False)
    op.create_index(op.f('ix_shippers_region'), 'shippers', ['region'], unique=False)
    op.create_index(op.f('ix_shippers_timeStamp'), 'shippers', ['timeStamp'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=60), nullable=False),
    sa.Column('productDescription', sa.String(length=255), nullable=False),
    sa.Column('productPrice', sa.Integer(), nullable=False),
    sa.Column('picturePath', sa.String(length=100), nullable=False),
    sa.Column('availableSize', sa.String(length=20), nullable=False),
    sa.Column('availableColor', sa.String(length=100), nullable=False),
    sa.Column('availableGender', sa.String(length=25), nullable=False),
    sa.Column('availableQuantity', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('availableDiscount', sa.Integer(), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('orderdetails_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orderdetails_id'], ['orderdetails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_availableColor'), 'products', ['availableColor'], unique=False)
    op.create_index(op.f('ix_products_availableDiscount'), 'products', ['availableDiscount'], unique=False)
    op.create_index(op.f('ix_products_availableGender'), 'products', ['availableGender'], unique=False)
    op.create_index(op.f('ix_products_availableQuantity'), 'products', ['availableQuantity'], unique=False)
    op.create_index(op.f('ix_products_availableSize'), 'products', ['availableSize'], unique=False)
    op.create_index(op.f('ix_products_discount'), 'products', ['discount'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_picturePath'), 'products', ['picturePath'], unique=False)
    op.create_index(op.f('ix_products_productDescription'), 'products', ['productDescription'], unique=False)
    op.create_index(op.f('ix_products_productName'), 'products', ['productName'], unique=False)
    op.create_index(op.f('ix_products_timeStamp'), 'products', ['timeStamp'], unique=False)
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brandName', sa.String(length=20), nullable=False),
    sa.Column('brandLogo', sa.String(length=30), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_brandLogo'), 'brand', ['brandLogo'], unique=False)
    op.create_index(op.f('ix_brand_brandName'), 'brand', ['brandName'], unique=False)
    op.create_index(op.f('ix_brand_timeStamp'), 'brand', ['timeStamp'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryName', sa.String(length=20), nullable=False),
    sa.Column('picPath', sa.String(length=100), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_categoryName'), 'category', ['categoryName'], unique=False)
    op.create_index(op.f('ix_category_picPath'), 'category', ['picPath'], unique=False)
    op.create_index(op.f('ix_category_timeStamp'), 'category', ['timeStamp'], unique=False)
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materialName', sa.String(length=20), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_materialName'), 'material', ['materialName'], unique=False)
    op.create_index(op.f('ix_material_timeStamp'), 'material', ['timeStamp'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=100), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_r'), 'rating', ['r'], unique=False)
    op.create_index(op.f('ix_rating_review'), 'rating', ['review'], unique=False)
    op.create_index(op.f('ix_rating_timeStamp'), 'rating', ['timeStamp'], unique=False)
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custID', sa.Integer(), nullable=False),
    sa.Column('companyName', sa.String(length=60), nullable=False),
    sa.Column('specialty', sa.String(length=60), nullable=False),
    sa.Column('companyLogo', sa.String(length=60), nullable=False),
    sa.Column('approved', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=60), nullable=False),
    sa.Column('additionalInfo', sa.String(length=60), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_additionalInfo'), 'sellers', ['additionalInfo'], unique=False)
    op.create_index(op.f('ix_sellers_address'), 'sellers', ['address'], unique=False)
    op.create_index(op.f('ix_sellers_approved'), 'sellers', ['approved'], unique=False)
    op.create_index(op.f('ix_sellers_city'), 'sellers', ['city'], unique=False)
    op.create_index(op.f('ix_sellers_companyLogo'), 'sellers', ['companyLogo'], unique=False)
    op.create_index(op.f('ix_sellers_companyName'), 'sellers', ['companyName'], unique=False)
    op.create_index(op.f('ix_sellers_region'), 'sellers', ['region'], unique=False)
    op.create_index(op.f('ix_sellers_specialty'), 'sellers', ['specialty'], unique=False)
    op.create_index(op.f('ix_sellers_timeStamp'), 'sellers', ['timeStamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_timeStamp'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_specialty'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_region'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_companyName'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_companyLogo'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_city'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_approved'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_address'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_additionalInfo'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_rating_timeStamp'), table_name='rating')
    op.drop_index(op.f('ix_rating_review'), table_name='rating')
    op.drop_index(op.f('ix_rating_r'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_material_timeStamp'), table_name='material')
    op.drop_index(op.f('ix_material_materialName'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_category_timeStamp'), table_name='category')
    op.drop_index(op.f('ix_category_picPath'), table_name='category')
    op.drop_index(op.f('ix_category_categoryName'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_brand_timeStamp'), table_name='brand')
    op.drop_index(op.f('ix_brand_brandName'), table_name='brand')
    op.drop_index(op.f('ix_brand_brandLogo'), table_name='brand')
    op.drop_table('brand')
    op.drop_index(op.f('ix_products_timeStamp'), table_name='products')
    op.drop_index(op.f('ix_products_productName'), table_name='products')
    op.drop_index(op.f('ix_products_productDescription'), table_name='products')
    op.drop_index(op.f('ix_products_picturePath'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_discount'), table_name='products')
    op.drop_index(op.f('ix_products_availableSize'), table_name='products')
    op.drop_index(op.f('ix_products_availableQuantity'), table_name='products')
    op.drop_index(op.f('ix_products_availableGender'), table_name='products')
    op.drop_index(op.f('ix_products_availableDiscount'), table_name='products')
    op.drop_index(op.f('ix_products_availableColor'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_shippers_timeStamp'), table_name='shippers')
    op.drop_index(op.f('ix_shippers_region'), table_name='shippers')
    op.drop_index(op.f('ix_shippers_phone2'), table_name='shippers')
    op.drop_index(op.f('ix_shippers_phone1'), table_name='shippers')
    op.drop_index(op.f('ix_shippers_email2'), table_name='shippers')
    op.drop_index(op.f('ix_shippers_email1'), table_name='shippers')
    op.drop_index(op.f('ix_shippers_companyName'), table_name='shippers')
    op.drop_index(op.f('ix_shippers_companyLogo'), table_name='shippers')
    op.drop_index(op.f('ix_shippers_city'), table_name='shippers')
    op.drop_index(op.f('ix_shippers_address'), table_name='shippers')
    op.drop_index(op.f('ix_shippers_additionalInfo'), table_name='shippers')
    op.drop_table('shippers')
    op.drop_index(op.f('ix_payment_transactionCode'), table_name='payment')
    op.drop_index(op.f('ix_payment_total'), table_name='payment')
    op.drop_index(op.f('ix_payment_timeStamp'), table_name='payment')
    op.drop_index(op.f('ix_payment_shipperPrice'), table_name='payment')
    op.drop_index(op.f('ix_payment_sellerReturns'), table_name='payment')
    op.drop_index(op.f('ix_payment_paidTotal'), table_name='payment')
    op.drop_index(op.f('ix_payment_dripQuotaTotal'), table_name='payment')
    op.drop_index(op.f('ix_payment_dripQuota'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_orderdetails_total'), table_name='orderdetails')
    op.drop_index(op.f('ix_orderdetails_timeStamp'), table_name='orderdetails')
    op.drop_index(op.f('ix_orderdetails_size'), table_name='orderdetails')
    op.drop_index(op.f('ix_orderdetails_quantity'), table_name='orderdetails')
    op.drop_index(op.f('ix_orderdetails_price'), table_name='orderdetails')
    op.drop_index(op.f('ix_orderdetails_fulfilledDate'), table_name='orderdetails')
    op.drop_index(op.f('ix_orderdetails_discount'), table_name='orderdetails')
    op.drop_index(op.f('ix_orderdetails_color'), table_name='orderdetails')
    op.drop_table('orderdetails')
    op.drop_index(op.f('ix_orders_timeStamp'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customers_timeStamp'), table_name='customers')
    op.drop_index(op.f('ix_customers_region'), table_name='customers')
    op.drop_index(op.f('ix_customers_pword'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone1'), table_name='customers')
    op.drop_index(op.f('ix_customers_lname'), table_name='customers')
    op.drop_index(op.f('ix_customers_fname'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_city'), table_name='customers')
    op.drop_index(op.f('ix_customers_address'), table_name='customers')
    op.drop_index(op.f('ix_customers_additionalInfo'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_admin_timeStamp'), table_name='admin')
    op.drop_index(op.f('ix_admin_pword'), table_name='admin')
    op.drop_index(op.f('ix_admin_phone2'), table_name='admin')
    op.drop_index(op.f('ix_admin_phone1'), table_name='admin')
    op.drop_index(op.f('ix_admin_lname'), table_name='admin')
    op.drop_index(op.f('ix_admin_fname'), table_name='admin')
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
