"""empty message

Revision ID: 3a3eb7db0c5a
Revises: 201bb8555a09
Create Date: 2020-02-29 03:33:32.820541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a3eb7db0c5a'
down_revision = '201bb8555a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rating_ibfk_1', 'rating', type_='foreignkey')
    op.drop_column('rating', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('rating_ibfk_1', 'rating', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###
