"""empty message

Revision ID: adedd5e23b54
Revises: 3a772372efcf
Create Date: 2020-03-11 13:17:22.333655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adedd5e23b54'
down_revision = '3a772372efcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orderdetails_ibfk_2', 'orderdetails', type_='foreignkey')
    op.create_foreign_key(None, 'orderdetails', 'products', ['product_id'], ['pid'])
    op.add_column('products', sa.Column('pid', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_products_pid'), 'products', ['pid'], unique=False)
    op.drop_index('ix_products_id', table_name='products')
    op.drop_column('products', 'id')
    op.drop_constraint('rating_ibfk_2', 'rating', type_='foreignkey')
    op.create_foreign_key(None, 'rating', 'products', ['product_id'], ['pid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.create_foreign_key('rating_ibfk_2', 'rating', 'products', ['product_id'], ['id'])
    op.add_column('products', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.drop_index(op.f('ix_products_pid'), table_name='products')
    op.drop_column('products', 'pid')
    op.drop_constraint(None, 'orderdetails', type_='foreignkey')
    op.create_foreign_key('orderdetails_ibfk_2', 'orderdetails', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
