"""empty message

Revision ID: e3c929c70e40
Revises: 3a3eb7db0c5a
Create Date: 2020-02-29 03:46:14.475105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3c929c70e40'
down_revision = '3a3eb7db0c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderdetails', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orderdetails', 'products', ['product_id'], ['id'])
    op.drop_constraint('products_ibfk_1', 'products', type_='foreignkey')
    op.drop_column('products', 'orderdetails_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('orderdetails_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('products_ibfk_1', 'products', 'orderdetails', ['orderdetails_id'], ['id'])
    op.drop_constraint(None, 'orderdetails', type_='foreignkey')
    op.drop_column('orderdetails', 'product_id')
    # ### end Alembic commands ###
