"""empty message

Revision ID: 1f07cefa31fe
Revises: 
Create Date: 2020-02-19 21:10:33.036041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f07cefa31fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('picPath', sa.String(length=100), nullable=True))
    op.alter_column('products', 'availableDiscount',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('products', 'discount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'ratingID',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'ratingID',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('products', 'discount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'availableDiscount',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('category', 'picPath')
    # ### end Alembic commands ###
