"""empty message

Revision ID: 4b6ddcb2e687
Revises: e3c929c70e40
Create Date: 2020-03-02 14:38:23.134005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6ddcb2e687'
down_revision = 'e3c929c70e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brandid', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('categoryid', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('materialid', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('sellerid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_brandid'), 'products', ['brandid'], unique=False)
    op.create_index(op.f('ix_products_categoryid'), 'products', ['categoryid'], unique=False)
    op.create_index(op.f('ix_products_materialid'), 'products', ['materialid'], unique=False)
    op.create_index(op.f('ix_products_sellerid'), 'products', ['sellerid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sellerid'), table_name='products')
    op.drop_index(op.f('ix_products_materialid'), table_name='products')
    op.drop_index(op.f('ix_products_categoryid'), table_name='products')
    op.drop_index(op.f('ix_products_brandid'), table_name='products')
    op.drop_column('products', 'sellerid')
    op.drop_column('products', 'materialid')
    op.drop_column('products', 'categoryid')
    op.drop_column('products', 'brandid')
    # ### end Alembic commands ###
