"""empty message

Revision ID: 4facbcd700a7
Revises: 
Create Date: 2020-03-11 13:51:40.785765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4facbcd700a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderdetails', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('orderdetails', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orderdetails', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'orderdetails', 'products', ['product_id'], ['id'])
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('transactionCode', sa.String(length=60), nullable=False))
    op.create_index(op.f('ix_orders_transactionCode'), 'orders', ['transactionCode'], unique=False)
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'])
    op.add_column('payment', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment', 'orders', ['order_id'], ['id'])
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.drop_index('ix_products_pid', table_name='products')
    op.drop_column('products', 'pid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_index('ix_products_pid', 'products', ['pid'], unique=False)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'order_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_transactionCode'), table_name='orders')
    op.drop_column('orders', 'transactionCode')
    op.drop_column('orders', 'customer_id')
    op.drop_constraint(None, 'orderdetails', type_='foreignkey')
    op.drop_constraint(None, 'orderdetails', type_='foreignkey')
    op.drop_column('orderdetails', 'product_id')
    op.drop_column('orderdetails', 'order_id')
    # ### end Alembic commands ###
