"""empty message

Revision ID: a4f6daa6e52b
Revises: a5e8e98c80a2
Create Date: 2020-03-10 16:22:20.771233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f6daa6e52b'
down_revision = 'a5e8e98c80a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('adultOrNot', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_products_adultOrNot'), 'products', ['adultOrNot'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_adultOrNot'), table_name='products')
    op.drop_column('products', 'adultOrNot')
    # ### end Alembic commands ###
