"""Added material column to Order-Details Table

Revision ID: c6eae3e9d7c6
Revises: ef7801cdd7dd
Create Date: 2021-07-15 01:45:26.070871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6eae3e9d7c6'
down_revision = 'ef7801cdd7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderdetails', sa.Column('material', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_orderdetails_material'), 'orderdetails', ['material'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderdetails_material'), table_name='orderdetails')
    op.drop_column('orderdetails', 'material')
    # ### end Alembic commands ###
